# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9670f701d5332dc0e886440fd2277221"
name = "VC Node"
application_url = "https://localhost:5173"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://localhost:5173/app/install" ]
